apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: json-server
  namespace: flux-system
spec:
  interval: 1m
  path: ./config/default
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: json-server

