apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: json-server
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/BlueTurtle-bytes/json-server.git
  ref:
    branch: main
  secretRef:
    name: json-server-git-auth
