name: CI - Build Controller Image

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: json-server-controller
  TTL: 2h

jobs:
  build-and-push:
    if: |
      !contains(github.event.head_commit.message, 'chore(gitops)')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push to ttl.sh
        run: |
          IMAGE=ttl.sh/${IMAGE_NAME}-${{ steps.vars.outputs.tag }}:${TTL}
          echo "Building and pushing $IMAGE"

          docker build \
            -t $IMAGE \
            .

          docker push $IMAGE

      - name: Output image reference
        run: |
          echo "Image pushed to:"
          echo "ttl.sh/${IMAGE_NAME}-${{ steps.vars.outputs.tag }}:${TTL}"


      - name: Update kustomization image
        run: |
          sed -i.bak \
            -e 's|newName: .*|newName: ttl.sh/${IMAGE_NAME}-${{ steps.vars.outputs.tag }|' \
            -e 's|newTag: .*|newTag: ${TTL}|' \
            config/manager/kustomization.yaml
          rm config/manager/kustomization.yaml.bak

      - name: Commit GitOps update
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add config/manager/kustomization.yaml
          git commit -m "chore(gitops): deploy controller image"
          git push