name: CI - Build Controller Image

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env:
  IMAGE_NAME: json-server-controller
  TTL: 2h   # <-- longer for Flux stability can increase for test demo

jobs:
  build-and-push:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, 'chore(gitops)')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image variables
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE="ttl.sh/${IMAGE_NAME}-${SHORT_SHA}:${TTL}"

          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT

      # multi-platform build
      - name: Build and push to ttl.sh
        run: |
          echo "Building and pushing ${{ steps.vars.outputs.image }}"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "${{ steps.vars.outputs.image }}" \
            --push \
            .

      - name: Update kustomization image
        run: |
          NEW_NAME="ttl.sh/${IMAGE_NAME}-${{ steps.vars.outputs.tag }}"
          sed -i.bak \
            -e "s|newName: .*|newName: ${NEW_NAME}|" \
            -e "s|newTag: .*|newTag: ${TTL}|" \
            config/manager/kustomization.yaml
          rm config/manager/kustomization.yaml.bak

      - name: Commit GitOps update
        if: github.event_name == 'push'
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add config/manager/kustomization.yaml
          git commit -m "chore(gitops): deploy controller image" || echo "No changes"
          git push
